#! /usr/bin/env python3
f=None
f=open('/home/alex/ux.csv', 'r', encoding='cp1251')

l=None
count=0
while f.readline()!=" ":
	count=count+1
	l=f.readline()	
	print(l);
    

f.close()



#! /usr/bin/env python3
f=None
f=open('/home/alex/ux.csv', 'r', encoding='cp1251')
d=None
d=open('/home/alex/ux2.csv', 'w', encoding='cp1251')
l=None
count=0
while f.readline()!=" ":
	count=count+1
	l=f.readline()	
	if l.find("A")
		pass
	else 
		d.writeline(l)
    

f.close()
d.close()



